# Generated by Django 5.0.1 on 2024-03-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('fish_name', models.CharField(max_length=50, verbose_name='মাছের নাম')),
                ('purchase_place', models.CharField(max_length=100, verbose_name='ক্রয়ের স্থান')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('fish_count', models.IntegerField(verbose_name='মাছের সংখ্যা')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মূল্য')),
                ('payment_method', models.CharField(max_length=50, verbose_name='পরিশোধের পদ্ধতি')),
                ('voucher', models.CharField(max_length=50, verbose_name='ভাউচার')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='অন্য বিশেষ তথ্য')),
            ],
            options={
                'verbose_name': 'মাছ ক্রয়',
                'verbose_name_plural': 'মাছ ক্রয় তথ্য',
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
