# Generated by Django 5.0.1 on 2024-03-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_fishpurchase_delete_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishpurchase',
            old_name='payment_method',
            new_name='ghere',
        ),
    ]
