# Generated by Django 5.0.1 on 2024-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_rename_payment_method_fishpurchase_ghere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishpurchase',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='ক্রয়ের স্থান'),
        ),
    ]
