# Generated by Django 5.0.1 on 2024-03-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0004_alter_fishpurchase_purchase_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishpurchase',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ক্রয়ের স্থান'),
        ),
    ]
