# Generated by Django 5.0.1 on 2024-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0005_alter_fishpurchase_purchase_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('expenditure_sector', models.CharField(max_length=100, verbose_name='ব্যায়ের খাত')),
                ('item_name', models.CharField(max_length=100, verbose_name='দ্রব্যের নামঃ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('unit', models.CharField(max_length=50, verbose_name='ইউনিট')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='খরচের পরিমাণ')),
                ('spender', models.CharField(max_length=100, verbose_name='খরচকারী')),
                ('voucher', models.CharField(max_length=100, verbose_name='ভাউচার')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='অন্য বিশেষ তথ্য')),
            ],
            options={
                'verbose_name': 'নৈমিত্তিক ব্যয়',
                'verbose_name_plural': 'নৈমিত্তিক ব্যয় তথ্য',
            },
        ),
    ]
