# Generated by Django 5.0.1 on 2024-03-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0007_fishpurchase_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishpurchase',
            name='log',
            field=models.CharField(blank=True, max_length=800, verbose_name='লগ'),
        ),
    ]
