# Generated by Django 5.0.1 on 2024-03-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0008_fishpurchase_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishpurchase',
            name='submitted_by',
        ),
    ]
