# Generated by Django 5.0.1 on 2024-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0009_remove_fishpurchase_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখঃ')),
                ('purpose', models.CharField(blank=True, max_length=80, null=True, verbose_name='ক্ষেত্র:')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Reason:')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity:')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Rate:')),
                ('personel', models.CharField(max_length=100, null=True, verbose_name='Personel:')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total:')),
                ('voucher', models.CharField(blank=True, max_length=100, null=True, verbose_name='ভাউচার')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('log', models.CharField(blank=True, max_length=800, verbose_name='লগ')),
            ],
        ),
        migrations.AddField(
            model_name='dailycost',
            name='log',
            field=models.CharField(blank=True, max_length=800, verbose_name='লগ'),
        ),
        migrations.AlterField(
            model_name='dailycost',
            name='voucher',
            field=models.CharField(blank=True, max_length=100, verbose_name='ভাউচার'),
        ),
    ]
