# Generated by Django 5.0.1 on 2024-04-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0010_salary_dailycost_log_alter_dailycost_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='personel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personel:'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity:'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate:'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason:'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total:'),
        ),
    ]
