# Generated by Django 5.0.1 on 2024-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0011_alter_salary_personel_alter_salary_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'বেতন/শ্রমিক', 'verbose_name_plural': 'বেতন/শ্রমিক তথ্য '},
        ),
        migrations.AlterField(
            model_name='dailycost',
            name='cost_amount',
            field=models.FloatField(verbose_name='খরচের পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='dailycost',
            name='quantity',
            field=models.FloatField(verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='fishpurchase',
            name='price',
            field=models.FloatField(verbose_name='মূল্য'),
        ),
        migrations.AlterField(
            model_name='fishpurchase',
            name='quantity',
            field=models.FloatField(verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate:'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total:'),
        ),
    ]
