# Generated by Django 5.0.1 on 2024-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
