# Generated by Django 5.0.1 on 2024-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_loginlog_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='role',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='site_name',
            field=models.CharField(default='Default Site Name', max_length=100),
        ),
    ]
