# Generated by Django 5.0.1 on 2024-04-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date:')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector:')),
                ('source', models.CharField(max_length=100, verbose_name='Source:')),
                ('fish_count', models.IntegerField(verbose_name='Quantity Per Unit:')),
                ('price', models.FloatField(verbose_name='Quantity:')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit:')),
                ('voucher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price:')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Memo:')),
                ('other_info', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comment:')),
                ('log', models.CharField(blank=True, max_length=800, verbose_name='লগ')),
            ],
        ),
    ]
